# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-spaces-demo',
                'doc_host': 'https://fastai.github.io',
                'git_url': 'https://github.com/fastai/nbdev-spaces-demo',
                'lib_path': 'nbdev_spaces_demo'},
  'syms': {'nbdev_spaces_demo.size': {'nbdev_spaces_demo.size.hfsize': ('size.html#hfsize', 'nbdev_spaces_demo/size.py')}}}